name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      # Deploy Storybook only when related files change
      - 'src/**/*.stories.@(js|jsx|ts|tsx|mdx)'
      - '.storybook/**'
      - 'package.json'
      - 'yarn.lock'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    name: Build & Deploy Storybook
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build Storybook
      - name: Build Storybook
        run: |
          export NODE_ENV=production
          yarn build:storybook

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload Storybook build as an artifact
      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './storybook-static'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
